# The URL the site will be built for
base_url = "https://corrode.dev"

theme = "ntun"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "kronuz"

[extra]
author = "Corrode Rust Consulting"
hero_image="hero/hero.svg"
city="D&uuml;sseldorf"
years="2023"

description = "by Matthias Endler"

links = [
    { url = "https://github.com/corrode", title="Github", icon = "github.svg"},
    { url = "https://twitter.com/matthiasendler", title="Twitter", icon = "twitter.svg"},
    { url = "https://www.linkedin.com/in/endlermatthias/", title="LinkedIn", icon = "linkedin.svg"},
    { url = "mailto:hi@corrode.dev", title="hi@corrode.dev", icon = "envelope.svg"}
]
