base_url = "https://corrode.dev"
title = "Corrode Rust Consulting"
description = "Friendly, professional Rust consulting and training. Writing content about idiomatic Rust."
author = "Matthias Endler"

compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "dracula", filename = "syntax-theme-dark-custom.css" },
    { theme = "kronuz", filename = "syntax-theme-light-custom.css" },
]

[extra]
author = "Corrode Rust Consulting"

links = [
    { url = "https://twitter.com/matthiasendler", title = "X", icon = "x.svg" },
    { url = "https://www.linkedin.com/company/corrode", title = "LinkedIn", icon = "linkedin.svg" },
    { url = "mailto:hi@corrode.dev", title = "hi@corrode.dev", icon = "envelope.svg" },
]
