base_url = "https://corrode.dev"
title = "Corrode Rust Consulting"
description = "Friendly, professional Rust consulting and training. Writing content about idiomatic Rust."
author = "Matthias Endler"

compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

[markdown]
smart_punctuation = true
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "dracula", filename = "syntax-theme-dark-custom.css" },
    { theme = "kronuz", filename = "syntax-theme-light-custom.css" },
]
bottom_footnotes = true

[extra]
author = "Corrode Rust Consulting"

links = [
    { url = "https://www.linkedin.com/company/corrode", title = "LinkedIn", icon = "linkedin.svg" },
    { url = "mailto:&#104;&#105;&#064;&#099;&#111;&#114;&#114;&#111;&#100;&#101;&#046;&#100;&#101;&#118;", title = "&#104;&#105;&#064;&#099;&#111;&#114;&#114;&#111;&#100;&#101;&#046;&#100;&#101;&#118;", icon = "envelope.svg" },
    { url = "https://twitter.com/matthiasendler", title = "X", icon = "x.svg" },
]
