name = "ntun-zola-theme"
description = "A classic resume theme"
license = "MIT"
homepage = "https://github.com/netoun/ntun"
# The minimum version of Zola required
min_version = "0.1.0"
# An optional live demo URL
demo = "https://netoun.github.io/ntun/"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Nicolas Coulonnier"
homepage = "https://netoun.com"